### PR TITLE
Problem with uwsgi on dotcloud, so there is a new way of doing this, again

### PR DESCRIPTION
**Pull request by twidi**
New way of overloading settings, with a simple call at the end of settings.py, without overloading django.conf.Settings (resolve a problem with dotcloud and uwsgi where this application was not working)

On the dotcloud hosting, they use nginx+uwsgi and django-Metasettings doesn't work. I don't know why, but it works fine in a `./manage.py shell` but not via the webserver.

So i rewrote your app to run this way : by adding a `mettasettings.init(global())` at the end of the `settings.py`, instead of the `__init__.py` of the project, we can just call the execfiles by passing the original `globals()` dict, and the work is magically done in this dict.

And there is no need to monkey-patch the `django.conf.Settings` class !

Tell me what you think about this way. 

PS : in github the diff seems horrible, but there is not so much changes !

### CODE REVIEW

**Comment by rspeed** [comment]
My early research for this project included using the output of locals(), but I hadn't considered using globals(). I had rejected locals() after reading warnings about how some interpreters (assumably Jython) wouldn't reflect changes made to the locals() output in the local scope. See http://docs.python.org/library/functions.html#locals. As a result, I assumed that was also the case for globals(), but I find no such warnings. I'll look into this, thanks!

**Comment by twidi** [comment]
Ok i'll read this.

I used `globals()` because on this page http://diveintopython.org/html_processing/locals_and_globals.html i read that `locasl()` is read-only !

**Comment by rspeed** [comment]
Indeed! According to Example 8.12 on that page, globals() is writeable.

Proceeding with running your code through some tests!

**Comment by rspeed** [comment]
Merged. Merci bien!

**Comment by twidi** [comment]
Cool ! De rien :)

**Pull request merged**
